version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:amd64
    restart: always
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_TAG}
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "${IP_ADDR}:53:53/tcp"
      - "${IP_ADDR}:53:53/udp"
    environment:
      DNS1: '10.0.0.2#5054'
      DNS2: 'no'
      IPv6: 'false'
      TZ: 'America/Chicago'
      DNSMASQ_LISTENING: 'all'
      WEBPASSWORD: '${ADMIN_PASSWORD}'
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - 'pihole_etc:/etc/pihole/'
      - 'pihole_dnsmasq:/etc/dnsmasq.d/'
      - 'pihole_certs:/etc/certs/:ro'
      - './external.conf:/etc/lighttpd/external.conf'

  letsencrypt:
    container_name: letsencrypt
    image: adferrand/letsencrypt-dns:${LE_TAG}
    environment:
      LETSENCRYPT_USER_MAIL: '${EMAIL}'
      LEXICON_PROVIDER: 'cloudflare'
      LEXICON_CLOUDFLARE_USERNAME: '${CF_USER}'
      LEXICON_CLOUDFLARE_TOKEN: '${CF_TOKEN}'
      DEPLOY_HOOK: 'gen_certs.sh'
      CERTS_USER_OWNER: '33'
      CERTS_GROUP_OWNER: '33'
      LETSENCRYPT_STAGING: '${LE_STAGING}'
    volumes:
      - ./le-domains.conf:/etc/letsencrypt/domains.conf
      - ./gen_certs.sh:/usr/local/bin/gen_certs.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - le_certs:/etc/letsencrypt
      - pihole_certs:/pihole_certs
    restart: always

volumes:
  pihole_etc:
  pihole_dnsmasq:
  le_certs:
  pihole_certs:

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
